# Generated by Django 3.2.4 on 2021-06-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_rename_contraseña_usuarios_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='comuna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasenia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
