# Generated by Django 3.2.4 on 2021-06-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0003_auto_20210614_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contrasenia', models.CharField(max_length=50, null=True)),
                ('comuna', models.CharField(max_length=50, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
